### PR TITLE
explanatory images + few improvements + ru translation + icons

### PR DESCRIPTION
**Pull request by quarkov**
Do you mind if I also redesign illustrations a little? Major idea is to place roots to the left and descendant nodes to the right; put trees in column aligned by the left page border (not in a row as it is now) - that will give extra place to explanations that I also suggest to draw.

### CODE REVIEW

**Comment by Philippe-Cholet** [comment]
There was a minor conflict between our master branches. I took your changes.

**Comment by Philippe-Cholet** [comment]
These images were generated by graphviz, I did not put hours on it to draw them (you can see the code to generate them in `if __name__ == '__main__':` section of `verification/tests.py`, it's quite short) so I'm not opposed to your idea, especially if you add explanatory images about paths.

You seems comfortable with image generation. I'm curious, which softwares do you use?

**Comment by Philippe-Cholet** [comment]
Do you want me to merge this PR and sync mission before the changes to come?
**PS:** I almost forgot: **thanks!**

**Comment by quarkov** [comment]
>>There was a minor conflict between our master branches. 

Yep, the master branch was ahead a bit.

>>You seems comfortable with image generation. I'm curious, which softwares do you use?

I use inkscape since it's a free one and it's developed for Linux =) 
But I used to make illustrations with ColerDraw back in time when I was on Windows. This one is really good. 
Both are for vector graphics design.

>>Do you want me to merge this PR and sync mission before the changes to come?

Let's sync the mission after I release the illustrations.

**Comment by quarkov** [comment]
@Philippe-Cholet 

I've finished, check the result please then merge.

**Comment by Philippe-Cholet** [comment]
For `basic-2.png` at the third explanatory image: `pair = (2, 6)` not `(2, 9)`.
Remains only task descriptions to see.

**Comment by Philippe-Cholet** [comment]
I'm not sure how image widths will be on checkio website: `max-width: 830px;` could be useful (or absolutely not) in img style. I would add it if necessary.
Update `basic-2.png` and I merge/sync it.

**Review by Philippe-Cholet — APPROVED** [review]
Great!

**Comment by Philippe-Cholet** [comment]
Old images displayed on checkio website.
**Edit:** no it's great after multiple refresh.

**Comment by quarkov** [comment]
>>Old images displayed on checkio website.

Usually it takes some time to replace one image with another. Not long, but anyway.

**Pull request merged**
